// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKM30y3Jedl0OujIPaN5Snf_PyN8_F5XI',
    appId: '1:89111061023:web:cdd2117794ebfcc9fb6b2a',
    messagingSenderId: '89111061023',
    projectId: 'my-bookly-app',
    authDomain: 'my-bookly-app.firebaseapp.com',
    storageBucket: 'my-bookly-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnG0d9ohQGK0qqwppXAuDYcxfqeApndJ0',
    appId: '1:89111061023:android:3a0e258bb145587dfb6b2a',
    messagingSenderId: '89111061023',
    projectId: 'my-bookly-app',
    storageBucket: 'my-bookly-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-K-xR8L6cIKzlo4Onc2za61upsjkFwY4',
    appId: '1:89111061023:ios:b8cf9750ae643ea9fb6b2a',
    messagingSenderId: '89111061023',
    projectId: 'my-bookly-app',
    storageBucket: 'my-bookly-app.firebasestorage.app',
    iosBundleId: 'com.example.myBooklyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-K-xR8L6cIKzlo4Onc2za61upsjkFwY4',
    appId: '1:89111061023:ios:b8cf9750ae643ea9fb6b2a',
    messagingSenderId: '89111061023',
    projectId: 'my-bookly-app',
    storageBucket: 'my-bookly-app.firebasestorage.app',
    iosBundleId: 'com.example.myBooklyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKM30y3Jedl0OujIPaN5Snf_PyN8_F5XI',
    appId: '1:89111061023:web:46a209c4f3deca37fb6b2a',
    messagingSenderId: '89111061023',
    projectId: 'my-bookly-app',
    authDomain: 'my-bookly-app.firebaseapp.com',
    storageBucket: 'my-bookly-app.firebasestorage.app',
  );
}
